### ISSUE TITLE
Fix the links in the tutorial examples

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#264]
Some links in the tutorial example (advanced usage, Kindergeld) do not work:
Ex.. The link where it should show the documentation for _`_kindergeld_m_tu_`_ example which is documented under 
 this link(see screenshot for the error): https://gettsim.readthedocs.io/en/latest/functions.html#gettsim.functions.kindergeld_m_hh
Also, same happens with the links related to nodes in the DAG plot 

- Fix the links in the tutorial example. Also, the nodes in the DAG plot should be linked with working links
### Screenshots/Error messages
![image](https://user-images.githubusercontent.com/77800456/105527729-5e572380-5ce4-11eb-9dc2-18c88374a6c5.png)

**Comment by hmgaudecker** [comment]
Thanks! I think that should be fixed in the development version already, @ChristianZimpelmann, can you check please?

And how about the 2021 parameters, @Eric-Sommer, time for a release?

**Comment by Eric-Sommer** [comment]
> And how about the 2021 parameters, @Eric-Sommer, time for a release?

With the exception of #256, they should be good to go.

**Comment by ChristianZimpelmann** [comment]
@hendshe, wher exactly did you find this link? I cannot locate it in the respective tutorial.

**Comment by hendshe** [comment]
@ChristianZimpelmann Thanks! https://gettsim.readthedocs.io/en/latest/functions.html#gettsim.functions.kindergeld_m_hh, However, I think, most of the links on this tutorial page give error messages (https://gettsim.readthedocs.io/en/stable/how_to_guides/visualizing_the_system.html)

**Comment by ChristianZimpelmann** [comment]
Thank you!

@davpahl took care of the tutorials, but this is indeed not fixed yet.

@davpahl @hendshe, does one of you would like to open a pull request and fix all broken links in the how-tos?

**Comment by hendshe** [comment]
Thanks, looking forward to having it fixed! As a user, I think I was mentioned here by mistake.

**Comment by davpahl** [comment]
Yes, I can work on that. Though after going through the tutorials, I am not sure what exactly needs to be changed as I am struggling to find the links in "advanced usage" that are not working.

Also, for me the nodes in DAGs link to the documentation correctly, but they do not work in the development version.

**Comment by ChristianZimpelmann** [comment]
> Thanks, looking forward to having it fixed! As a user, I think I was mentioned here by mistake.

Every user is welcome to become a contributor :)

**Comment by ChristianZimpelmann** [comment]
@hendshe, can you please check if all your issues are solved by #266 ?

You can check this link: https://gettsim--266.org.readthedocs.build/en/266/

**Comment by hendshe** [comment]
Thanks @ChristianZimpelmann! Would you like that I check out this version: https://gettsim--266.org.readthedocs.build/en/266/? Also, could you please send the link for downloading tutorial folder to open it in a notebook?  (the version after you applied the changes).

**Comment by ChristianZimpelmann** [comment]
Yes, that would be great!

You find the Notebooks in this repo under docs/tutorials

**Comment by hendshe** [comment]
Thanks! I downloaded it to be able to follow up with your recent changes and just checked using the Notebook for advanced usage, and tried running this DAG plot using the below-command similar to what is given on the tutorial's link( but for a different output variable), clicking on the nodes navigate to links where errors still appear, did you fix it for the given tutorial's example (i.e for that "kindergeld_m" output variable) or for all? Here below you may find a screenshot.
```
selectors = {"type": "neighbors", "node": "arbeitsl_geld_2_m_hh", "order": 2}
plot_dag(functions=policy_functions, selectors=selectors);
![image](https://user-images.githubusercontent.com/77800456/108396322-0219ed80-7217-11eb-830f-80d982d736c1.png)

```
![image](https://user-images.githubusercontent.com/77800456/108397174-fd096e00-7217-11eb-8db2-a3dc07b85a5a.png)

**Comment by ChristianZimpelmann** [comment]
In the released version this is not updated yet. So you need to check https://gettsim--266.org.readthedocs.build/en/266/

**Comment by hendshe** [comment]
Thanks! I think that link works well. Then, this issue here should be closed now, or?
